quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      initial-size: 5
      max-size: 20
      min-size: 5
      acquisition-timeout: 10s

  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
    jdbc:
      statement-batch-size: 50
    second-level-cache-enabled: true

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    schemas: public
    validate-on-migrate: true

  native:
    add-all-charsets: false
    cleanup-server: true